var courses = [
    {
        "id": 1,
        "img": "https://i.imgur.com/kNULtoW.jpg",
        "name": "The Python Mega Course: Build 10 Real World Applications",
        "instructor": "Leanne Graham",
        "courseDuration": '25h 18min',
        "amount": 50.99,
    },
    {
        "id": 2,
        "img": "https://i.imgur.com/JXLmAAQ.jpg",
        "name": "The Complete JavaScript Course 2020: Build Real Projects!",
        "instructor": "Ervin Howell",
        "courseDuration": '27h 55min',
        "amount": 60
    },
    {
        "id": 3,
        "img": "https://i.imgur.com/EhcI9UI.jpg",
        "name": "Java Programming Masterclass for Software Developers",
        "instructor": "Clementine Bauch",
        "courseDuration": '80h 5min',
        "amount": 100,
    },
    {
        "id": 4,
        "img": "https://i.imgur.com/kc8Hwkj.jpg",
        "name": "C Programming Masterclass for Software Developers",
        "instructor": "Patricia Lebsack",
        "courseDuration": '30h 50min',
        "amount": 80,
    },
    {
        "id": 5,
        "img": "https://i.imgur.com/gDRR9WO.jpg",
        "name": "C# for complete beginner",
        "instructor": "Chelsey Dietrich",
        "courseDuration": '18h 20min',
        "amount": 80,
    },
    {
        "id": 6,
        "img": "https://i.imgur.com/W2rqi4L.jpg",
        "name": "Complete C++ course , Beginner to Advanced",
        "instructor": "Mrs. Dennis Schulist",
        "courseDuration": '22h 20min',
        "amount": 120,
    },
    {
        "id": 7,
        "img": "https://i.imgur.com/LGcizyU.jpg",
        "name": "Go , beginner to advance",
        "instructor": "Kurtis Weissnat",
        "courseDuration": '19h 10min',
        "amount": 110,
    },
    {
        "id": 8,
        "img": "https://i.imgur.com/w6BSfqb.jpg",
        "name": "Complete PHP course , Beginner to Advanced",
        "instructor": "Nicholas Runolfsdottir V",
        "courseDuration": '23h 59min',
        "amount": 130,
    },
    {
        "id": 9,
        "img": "https://i.imgur.com/0nd4eVY.jpg",
        "name": "Swift for complete beginner",
        "instructor": "Glenna Reichert",
        "courseDuration": '15h 20min',
        "amount": 35,
    },
    {
        "id": 10,
        "img": "https://i.imgur.com/lxhZXIO.jpg",
        "name": "Ruby for web developing",
        "instructor": "Jhon Reichert",
        "courseDuration": '12h 10min',
        "amount": 45,
    },
    {
        "id": 11,
        "img": "https://i.imgur.com/o0uSehi.jpg",
        "name": "Complete Angular course for web developing",
        "instructor": "Fida Hossain V",
        "courseDuration": '19h 35min',
        "amount": 85,
    },
    {
        "id": 12,
        "img": "https://i.imgur.com/0HOs1Qb.jpg",
        "name": "Typescript course for advanced javascript developer",
        "instructor": "Labib KGR",
        "courseDuration": '10h 25min',
        "amount": 99.99,
    },
    {
        "id": 13,
        "img": "https://i.imgur.com/SlF0dZ7.jpg",
        "name": "HTML course for complete beginner",
        "instructor": "Iltimuas Fotka",
        "courseDuration": '11h 25min',
        "amount": 25,
    },
    {
        "id": 14,
        "img": "https://i.imgur.com/srGsmlD.jpg",
        "name": "CSS course for web designer",
        "instructor": "Shohan Hablu",
        "courseDuration": '16h 15min',
        "amount": 42,
    },
    {
        "id": 15,
        "img": "https://i.imgur.com/5AvUdai.jpg",
        "name": "NodeJS from beginner to advance",
        "instructor": "Clementina DuBuque",
        "courseDuration": '9h 15min',
        "amount": 75,
    }
]
export default courses;